### PR TITLE
Throttle websocket to prevent clients from drowning in data

### PR DESCRIPTION
**Pull request by FiberJW**
This should help with lionshare performance by slowing down the faucet of data.

### CODE REVIEW

**Review by maksim-s — CHANGES_REQUESTED** [review]
thanks @fiber-god! 👏 Can you please remove the stylistic changes from this PR? While I like them, I don't want the project to end up with inconsistent style between different files. If you feel strongly about it, would love to see a PR updating all the files.

**Comment by FiberJW** [comment]
Yeah, sorry. Prettier autoformatted the files. Wouldn't mind submitting a
pr to fully support Prettier in this codebase so that there's one unified
code style.

**Comment by maksim-s** [comment]
a separate PR with prettier would be awesome!

**Comment by FiberJW** [comment]
Just submitted #45. Will update this branch based on that PR if merged.

**Comment by FiberJW** [comment]
Everything should be consistently styled now

**Comment by maksim-s** [comment]
thank you!

**Pull request merged**
